name: database_project
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=4.2.0=pyhd8ed1ab_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.12.12=haa95532_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py311ha68e1ae_0
  - click=8.1.7=win_pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=41.0.7=py311h7cb4080_1
  - dnspython=2.4.2=pyhd8ed1ab_1
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hd77b12b_0
  - flask=3.0.0=pyhd8ed1ab_0
  - flask-wtf=1.2.1=pyhd8ed1ab_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=72.1=h63175ca_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - libabseil=20230802.1=cxx17_h63175ca_0
  - libevent=2.1.12=h3671451_1
  - libffi=3.4.4=hd77b12b_0
  - libprotobuf=3.21.12=h12be248_2
  - libzlib=1.2.13=hcfcfb64_5
  - lz4-c=1.9.4=hcfcfb64_0
  - markupsafe=2.1.3=py311h2bbff1b_0
  - mysql=8.0.33=h9c18f36_0
  - mysql-client=8.0.33=hed9f4ee_0
  - mysql-common=8.0.33=hde014ed_0
  - mysql-connector-python=8.0.31=py311hc774530_2
  - mysql-devel=8.0.33=hde014ed_0
  - mysql-libs=8.0.33=h8b0d2c3_0
  - mysql-server=8.0.33=hdf5bdb2_0
  - openssl=3.2.0=hcfcfb64_1
  - pip=23.3.1=py311haa95532_0
  - protobuf=4.21.12=py311h12c1d0e_0
  - pycparser=2.21=pyhd8ed1ab_0
  - python=3.11.5=he1021f5_0
  - python_abi=3.11=2_cp311
  - setuptools=68.2.2=py311haa95532_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023c=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.41.2=py311haa95532_0
  - wtforms=3.0.1=pyhd8ed1ab_0
  - xz=5.4.5=h8cc25b3_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zstd=1.5.5=h12be248_0
prefix: C:\Users\George\anaconda3\envs\database_project
